### ISSUE TITLE
Swagger ver 2 support?

### ISSUE THREAD

**Issue by cmshawns** [skrusty/dotswaggen#4]
I see that the readme mentioned versions 1.2 and 1.1. Are there plans to support version 2.0?

**Comment by skrusty** [comment]
Yes, I need to commit some new code to handle version selection based on the swagger input file. Although 2.0 support is not top of my list, so once that code is checked in, by all means contributions are welcome.

**Comment by sterkinternet** [comment]
@skrusty can you commit the new code?

**Comment by skrusty** [comment]
It's not finished! I've not had time to work on this for some time, and only really made a small start on it. However, if you wanted to implement it yourself please feel free to make a pull request, I'd happily look at including it in dotswaggen.
